
package eventapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author aenni
 */
public class EventGUI extends javax.swing.JFrame {

    //declare variables and objects
    String date, location;
    Boolean state;
    private ArrayList <Event> eList;
    
    public EventGUI() {
        //window title
        super("Events Calendar Program - NCI");
        initComponents();

        //create variables
        date = new String();
        location = new String();

        //create arrayList
        eList = new ArrayList <>();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avivaD = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        crokeD = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        thomondD = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        kingspanD = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        viewE = new javax.swing.JButton();
        addE = new javax.swing.JButton();
        printE = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        viewP = new javax.swing.JPanel();
        avivaB = new javax.swing.JButton();
        crokeB = new javax.swing.JButton();
        kingspanB = new javax.swing.JButton();
        thomondB = new javax.swing.JButton();
        avivaLabel = new javax.swing.JLabel();
        crokeLabel = new javax.swing.JLabel();
        kingspanLabel = new javax.swing.JLabel();
        thomondLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        addP = new javax.swing.JPanel();
        instructionsJL = new javax.swing.JLabel();
        showJB = new javax.swing.JButton();
        sportJB = new javax.swing.JButton();
        dateJL = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        headlineJL = new javax.swing.JLabel();
        supportJL = new javax.swing.JLabel();
        headlineTF = new javax.swing.JTextField();
        supportTF = new javax.swing.JTextField();
        t1JL = new javax.swing.JLabel();
        t2JL = new javax.swing.JLabel();
        t1TF = new javax.swing.JTextField();
        t2TF = new javax.swing.JTextField();
        locationJL = new javax.swing.JLabel();
        saveNew = new javax.swing.JButton();
        clearForm = new javax.swing.JButton();
        avivaRB = new javax.swing.JRadioButton();
        crokeRB = new javax.swing.JRadioButton();
        kingspanRB = new javax.swing.JRadioButton();
        thomondRB = new javax.swing.JRadioButton();
        sep1 = new javax.swing.JSeparator();
        displayB = new javax.swing.JButton();

        avivaD.setMinimumSize(new java.awt.Dimension(800, 450));

        jLabel2.setText("Upcoming Events at Aviva Stadium");

        javax.swing.GroupLayout avivaDLayout = new javax.swing.GroupLayout(avivaD.getContentPane());
        avivaD.getContentPane().setLayout(avivaDLayout);
        avivaDLayout.setHorizontalGroup(
            avivaDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avivaDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        avivaDLayout.setVerticalGroup(
            avivaDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avivaDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        crokeD.setMinimumSize(new java.awt.Dimension(800, 450));

        jLabel3.setText("Events at Croke Park");

        javax.swing.GroupLayout crokeDLayout = new javax.swing.GroupLayout(crokeD.getContentPane());
        crokeD.getContentPane().setLayout(crokeDLayout);
        crokeDLayout.setHorizontalGroup(
            crokeDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crokeDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        crokeDLayout.setVerticalGroup(
            crokeDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crokeDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        thomondD.setMinimumSize(new java.awt.Dimension(800, 450));

        jLabel4.setText("Upcoming Events at Thomond Park");

        javax.swing.GroupLayout thomondDLayout = new javax.swing.GroupLayout(thomondD.getContentPane());
        thomondD.getContentPane().setLayout(thomondDLayout);
        thomondDLayout.setHorizontalGroup(
            thomondDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thomondDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        thomondDLayout.setVerticalGroup(
            thomondDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thomondDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        kingspanD.setMinimumSize(new java.awt.Dimension(800, 450));

        jLabel5.setText("Upcoming Events at the Kingspan Stadium");

        javax.swing.GroupLayout kingspanDLayout = new javax.swing.GroupLayout(kingspanD.getContentPane());
        kingspanD.getContentPane().setLayout(kingspanDLayout);
        kingspanDLayout.setHorizontalGroup(
            kingspanDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kingspanDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        kingspanDLayout.setVerticalGroup(
            kingspanDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kingspanDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        viewE.setText("View Events");
        viewE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEActionPerformed(evt);
            }
        });

        addE.setText("Add Event");
        addE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEActionPerformed(evt);
            }
        });

        printE.setText("Save to File");
        printE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printEActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewE)
                    .addComponent(printE)
                    .addComponent(addE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new java.awt.CardLayout());

        viewP.setBackground(new java.awt.Color(153, 255, 153));
        viewP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        avivaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/images/aviva.jpg"))); // NOI18N
        avivaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avivaBActionPerformed(evt);
            }
        });

        crokeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/images/croke.jpg"))); // NOI18N
        crokeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crokeBActionPerformed(evt);
            }
        });

        kingspanB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/images/thomond.jpg"))); // NOI18N
        kingspanB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kingspanBActionPerformed(evt);
            }
        });

        thomondB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/images/kingspan.jpg"))); // NOI18N
        thomondB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thomondBActionPerformed(evt);
            }
        });

        avivaLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        avivaLabel.setText("AVIVA STADIUM");

        crokeLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        crokeLabel.setText("CROKE PARK");

        kingspanLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        kingspanLabel.setText("KINGSPAN STADIUM");

        thomondLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        thomondLabel.setText("THOMOND PARK");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        jLabel1.setText("VIEW EVENTS BY LOCATION");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout viewPLayout = new javax.swing.GroupLayout(viewP);
        viewP.setLayout(viewPLayout);
        viewPLayout.setHorizontalGroup(
            viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator6)
                    .addComponent(avivaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thomondB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(viewPLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(avivaLabel))
                    .addComponent(kingspanLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator5))
                .addGap(112, 112, 112)
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(crokeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kingspanB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(viewPLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(crokeLabel))
                    .addGroup(viewPLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(thomondLabel))
                    .addComponent(jSeparator7))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(238, 238, 238))
        );
        viewPLayout.setVerticalGroup(
            viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewPLayout.createSequentialGroup()
                        .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(avivaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crokeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avivaLabel)
                            .addComponent(crokeLabel)))
                    .addComponent(jSeparator1))
                .addGap(18, 18, 18)
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPLayout.createSequentialGroup()
                        .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thomondB)
                            .addComponent(kingspanB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kingspanLabel)
                            .addComponent(thomondLabel)))
                    .addGroup(viewPLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel2.add(viewP, "card2");

        addP.setBackground(new java.awt.Color(153, 204, 255));

        instructionsJL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        instructionsJL.setText("Please select the type of event:");

        showJB.setText("Concert / Show");
        showJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showJBActionPerformed(evt);
            }
        });

        sportJB.setText("Sport");
        sportJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportJBActionPerformed(evt);
            }
        });

        dateJL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateJL.setText("Date:");

        dateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTFActionPerformed(evt);
            }
        });

        headlineJL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headlineJL.setText("Headline:");

        supportJL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        supportJL.setText("Support:");

        supportTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportTFActionPerformed(evt);
            }
        });

        t1JL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1JL.setText("Team 1:");

        t2JL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t2JL.setText("Team 2:");

        t1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1TFActionPerformed(evt);
            }
        });

        locationJL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        locationJL.setText("Location:");

        saveNew.setText("Save Event");
        saveNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNewActionPerformed(evt);
            }
        });

        clearForm.setText("Clear Form");
        clearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormActionPerformed(evt);
            }
        });

        avivaRB.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup2.add(avivaRB);
        avivaRB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        avivaRB.setForeground(new java.awt.Color(255, 255, 255));
        avivaRB.setText("Aviva Stadium");

        crokeRB.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup2.add(crokeRB);
        crokeRB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        crokeRB.setForeground(new java.awt.Color(255, 255, 255));
        crokeRB.setText("Croke Park");

        kingspanRB.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup2.add(kingspanRB);
        kingspanRB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kingspanRB.setForeground(new java.awt.Color(255, 255, 255));
        kingspanRB.setText("Kingspan Stadium");

        thomondRB.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup2.add(thomondRB);
        thomondRB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thomondRB.setForeground(new java.awt.Color(255, 255, 255));
        thomondRB.setText("Thomond Park");

        displayB.setText("displayB");
        displayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPLayout = new javax.swing.GroupLayout(addP);
        addP.setLayout(addPLayout);
        addPLayout.setHorizontalGroup(
            addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPLayout.createSequentialGroup()
                        .addComponent(instructionsJL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showJB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sportJB)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPLayout.createSequentialGroup()
                        .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateJL)
                            .addComponent(locationJL)
                            .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(t1JL)
                                .addComponent(headlineJL)))
                        .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(433, 433, 433))
                            .addGroup(addPLayout.createSequentialGroup()
                                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(addPLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveNew)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearForm))
                                    .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addPLayout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addComponent(avivaRB)
                                            .addGap(18, 18, 18)
                                            .addComponent(crokeRB)
                                            .addGap(18, 18, 18)
                                            .addComponent(kingspanRB)
                                            .addGap(18, 18, 18)
                                            .addComponent(thomondRB))
                                        .addGroup(addPLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(headlineTF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(supportJL)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(supportTF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(displayB)
                                            .addGroup(addPLayout.createSequentialGroup()
                                                .addComponent(t1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(t2JL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(t2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(addPLayout.createSequentialGroup()
                        .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        addPLayout.setVerticalGroup(
            addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructionsJL)
                    .addComponent(showJB)
                    .addComponent(sportJB)
                    .addComponent(clearForm)
                    .addComponent(saveNew))
                .addGap(20, 20, 20)
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationJL)
                    .addComponent(avivaRB)
                    .addComponent(crokeRB)
                    .addComponent(kingspanRB)
                    .addComponent(thomondRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateJL)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPLayout.createSequentialGroup()
                        .addComponent(headlineJL)
                        .addGap(18, 18, 18)
                        .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1JL)
                            .addComponent(t1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2JL)
                            .addComponent(t2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(headlineTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(supportJL)
                        .addComponent(supportTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109)
                .addComponent(displayB)
                .addContainerGap(479, Short.MAX_VALUE))
        );

        jPanel2.add(addP, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avivaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avivaBActionPerformed
        avivaD.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_avivaBActionPerformed

    private void printEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printEActionPerformed

    private void addEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEActionPerformed
        viewP.setVisible(false);
        addP.setVisible(true);
    }//GEN-LAST:event_addEActionPerformed

    private void viewEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEActionPerformed
        viewP.setVisible(true);
        addP.setVisible(false);
    }//GEN-LAST:event_viewEActionPerformed

    private void crokeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crokeBActionPerformed
        crokeD.setVisible(true);
    }//GEN-LAST:event_crokeBActionPerformed

    private void thomondBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thomondBActionPerformed
        thomondD.setVisible(true);
    }//GEN-LAST:event_thomondBActionPerformed

    private void kingspanBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kingspanBActionPerformed
        kingspanD.setVisible(true);
    }//GEN-LAST:event_kingspanBActionPerformed

    private void clearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormActionPerformed

        //Clear button code to clear all text fields so the user can re-enter new event details. Also restores to original view.
        dateTF.setText("");
        headlineTF.setText("");
        supportTF.setText("");
        t1TF.setText("");
        t2TF.setText("");

        dateTF.setVisible(true);
        dateJL.setVisible(true);
        headlineTF.setVisible(false);
        supportTF.setVisible(false);
        headlineJL.setVisible(false);
        supportJL.setVisible(false);
        t1JL.setVisible(false);
        t2JL.setVisible(false);
        t1TF.setVisible(false);
        t2TF.setVisible(false);
    }//GEN-LAST:event_clearFormActionPerformed

    private void saveNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNewActionPerformed

        if(state == true) {
            Concert e = new Concert();
            
                if (avivaRB.isSelected()) {
                    location = "Aviva Stadium";
                } else if (crokeRB.isSelected()) {
                    location = "Croke Park";
                } else if (thomondRB.isSelected()) {
                    location = "Thomond Park";
                } else if(kingspanRB.isSelected()){
                    location = "Kingspan Stadium";
                }            
            
            e.setLocation(location);
            e.setDate(dateTF.getText());
            e.setHeadline(headlineTF.getText());
            e.setSupport(supportTF.getText());
            
            
            eList.add(e);
        }
        
        if(state == false) {
            Sport e = new Sport();
            
                if (avivaRB.isSelected()) {
                    location = "Aviva Stadium";
                } else if (crokeRB.isSelected()) {
                    location = "Croke Park";
                } else if (thomondRB.isSelected()) {
                    location = "Thomond Park";
                } else if(kingspanRB.isSelected()){
                    location = "Kingspan Stadium";
                }
                
            e.setLocation(location);
            e.setDate(dateTF.getText());
            e.setTeam1(t1TF.getText());
            e.setTeam2(t2TF.getText());
            
            eList.add(e);
            
            JOptionPane.showMessageDialog(null, "The following information has been added to the Event calendar: \n Location: "+location+"\n Date: "+date+"\n ");
        }
    }//GEN-LAST:event_saveNewActionPerformed

    private void t1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1TFActionPerformed

    private void supportTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supportTFActionPerformed

    private void dateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTFActionPerformed

    private void sportJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportJBActionPerformed
        state = false;
        dateTF.setVisible(true);
        dateJL.setVisible(true);
        headlineTF.setVisible(false);
        supportTF.setVisible(false);
        headlineJL.setVisible(false);
        supportJL.setVisible(false);
        t1JL.setVisible(true);
        t2JL.setVisible(true);
        t1TF.setVisible(true);
        t2TF.setVisible(true);
    }//GEN-LAST:event_sportJBActionPerformed

    private void showJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showJBActionPerformed
        state = true;
        dateTF.setVisible(true);
        dateJL.setVisible(true);
        headlineTF.setVisible(true);
        supportTF.setVisible(true);
        headlineJL.setVisible(true);
        supportJL.setVisible(true);
        t1JL.setVisible(false);
        t2JL.setVisible(false);
        t1TF.setVisible(false);
        t2TF.setVisible(false);
    }//GEN-LAST:event_showJBActionPerformed

    private void displayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBActionPerformed
        for(int i = 0; i < arr.length; i++){
            JOptionPane.showMessageDialog(null, "location: "+arr[i].getLocation()+"\n date: "+arr[i].getDate());
        }
    }//GEN-LAST:event_displayBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addE;
    private javax.swing.JPanel addP;
    private javax.swing.JButton avivaB;
    private javax.swing.JDialog avivaD;
    private javax.swing.JLabel avivaLabel;
    private javax.swing.JRadioButton avivaRB;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clearForm;
    private javax.swing.JButton crokeB;
    private javax.swing.JDialog crokeD;
    private javax.swing.JLabel crokeLabel;
    private javax.swing.JRadioButton crokeRB;
    private javax.swing.JLabel dateJL;
    private javax.swing.JTextField dateTF;
    private javax.swing.JButton displayB;
    private javax.swing.JLabel headlineJL;
    private javax.swing.JTextField headlineTF;
    private javax.swing.JLabel instructionsJL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton kingspanB;
    private javax.swing.JDialog kingspanD;
    private javax.swing.JLabel kingspanLabel;
    private javax.swing.JRadioButton kingspanRB;
    private javax.swing.JLabel locationJL;
    private javax.swing.JButton printE;
    private javax.swing.JButton saveNew;
    private javax.swing.JSeparator sep1;
    private javax.swing.JButton showJB;
    private javax.swing.JButton sportJB;
    private javax.swing.JLabel supportJL;
    private javax.swing.JTextField supportTF;
    private javax.swing.JLabel t1JL;
    private javax.swing.JTextField t1TF;
    private javax.swing.JLabel t2JL;
    private javax.swing.JTextField t2TF;
    private javax.swing.JButton thomondB;
    private javax.swing.JDialog thomondD;
    private javax.swing.JLabel thomondLabel;
    private javax.swing.JRadioButton thomondRB;
    private javax.swing.JButton viewE;
    private javax.swing.JPanel viewP;
    // End of variables declaration//GEN-END:variables
}
