/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventapp;

import java.io.*;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x15011887
 */
public class EventGUI extends javax.swing.JFrame {
    
    String location, date, name, type;
    boolean state;
    private ArrayList <Event> eList;

    /**
     * Creates new form EventGUI
     */
    public EventGUI() {
        super("Event Calendar / Fixture List - NCI | OOP");
        initComponents();
        
        //create variables
        location = new String();
        date = new String();
        
        //create arrayList
        eList = new ArrayList <> ();
        
        contentP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationBtnGroup = new javax.swing.ButtonGroup();
        navP = new javax.swing.JPanel();
        viewB = new javax.swing.JButton();
        addB = new javax.swing.JButton();
        contentP = new javax.swing.JPanel();
        viewP = new javax.swing.JPanel();
        avivaBtn = new javax.swing.JButton();
        avivaLabel = new javax.swing.JLabel();
        crokeBtn = new javax.swing.JButton();
        crokeLabel = new javax.swing.JLabel();
        kingspanBtn = new javax.swing.JButton();
        kingspanLabel = new javax.swing.JLabel();
        thomondBtn = new javax.swing.JButton();
        thomondLabel = new javax.swing.JLabel();
        addP = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        concertBtn = new javax.swing.JButton();
        matchBtn = new javax.swing.JButton();
        locationLabel = new javax.swing.JLabel();
        avivaRB = new javax.swing.JRadioButton();
        crokeRB = new javax.swing.JRadioButton();
        thomondRB = new javax.swing.JRadioButton();
        kingspanRB = new javax.swing.JRadioButton();
        dateLabel = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        homeLabel = new javax.swing.JLabel();
        homeTF = new javax.swing.JTextField();
        awayLabel = new javax.swing.JLabel();
        awayTF = new javax.swing.JTextField();
        headlineLabel = new javax.swing.JLabel();
        headlineTF = new javax.swing.JTextField();
        supportLabel = new javax.swing.JLabel();
        supportTF = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        displayArray = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navP.setBorder(javax.swing.BorderFactory.createTitledBorder("Navigation"));

        viewB.setText("View Events");
        viewB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBActionPerformed(evt);
            }
        });

        addB.setText("Add Event");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPLayout = new javax.swing.GroupLayout(navP);
        navP.setLayout(navPLayout);
        navPLayout.setHorizontalGroup(
            navPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navPLayout.setVerticalGroup(
            navPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(navPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewB)
                    .addComponent(addB))
                .addContainerGap())
        );

        contentP.setBorder(javax.swing.BorderFactory.createTitledBorder("Content"));
        contentP.setLayout(new java.awt.CardLayout());

        viewP.setBorder(javax.swing.BorderFactory.createTitledBorder("View Events"));

        avivaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/images/aviva.jpg"))); // NOI18N

        avivaLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        avivaLabel.setText("AVIVA STADIUM");

        crokeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/images/croke.jpg"))); // NOI18N

        crokeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        crokeLabel.setText("CROKE PARK");

        kingspanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/images/kingspan.jpg"))); // NOI18N

        kingspanLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kingspanLabel.setText("KINGSPAN STADIUM");

        thomondBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventapp/images/thomond.jpg"))); // NOI18N

        thomondLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        thomondLabel.setText("THOMOND PARK");

        javax.swing.GroupLayout viewPLayout = new javax.swing.GroupLayout(viewP);
        viewP.setLayout(viewPLayout);
        viewPLayout.setHorizontalGroup(
            viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPLayout.createSequentialGroup()
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avivaBtn)
                            .addComponent(kingspanBtn)
                            .addGroup(viewPLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(avivaLabel))))
                    .addGroup(viewPLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(kingspanLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thomondBtn)
                    .addComponent(crokeBtn)
                    .addGroup(viewPLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(crokeLabel))
                    .addGroup(viewPLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(thomondLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        viewPLayout.setVerticalGroup(
            viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avivaBtn)
                    .addComponent(crokeBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avivaLabel)
                    .addComponent(crokeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kingspanBtn)
                    .addComponent(thomondBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kingspanLabel)
                    .addComponent(thomondLabel))
                .addGap(24, 24, 24))
        );

        contentP.add(viewP, "card3");

        addP.setBorder(javax.swing.BorderFactory.createTitledBorder("Add New Event"));

        typeLabel.setDisplayedMnemonic('E');
        typeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        typeLabel.setText("Event Type:");

        concertBtn.setText("Concert");
        concertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concertBtnActionPerformed(evt);
            }
        });

        matchBtn.setText("Match");
        matchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchBtnActionPerformed(evt);
            }
        });

        locationLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        locationLabel.setText("Event Location:");

        locationBtnGroup.add(avivaRB);
        avivaRB.setText("Aviva Stadium");

        locationBtnGroup.add(crokeRB);
        crokeRB.setText("Croke Park");

        locationBtnGroup.add(thomondRB);
        thomondRB.setText("Thomond Park");

        locationBtnGroup.add(kingspanRB);
        kingspanRB.setText("Kingspan Stadium");

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateLabel.setText("Date:");

        homeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        homeLabel.setText("Home Team:");

        awayLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        awayLabel.setText("Away Team: ");

        headlineLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        headlineLabel.setText("Headline:");

        supportLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supportLabel.setText("Support:");

        clearBtn.setBackground(new java.awt.Color(255, 0, 0));
        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("CLEAR FORM");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        submitBtn.setBackground(new java.awt.Color(0, 204, 0));
        submitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("SUBMIT FORM");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        displayArray.setText("displayArray");
        displayArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayArrayActionPerformed(evt);
            }
        });

        exportBtn.setText("Export Event List");
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPLayout = new javax.swing.GroupLayout(addP);
        addP.setLayout(addPLayout);
        addPLayout.setHorizontalGroup(
            addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPLayout.createSequentialGroup()
                        .addComponent(locationLabel)
                        .addGap(18, 18, 18)
                        .addComponent(avivaRB)
                        .addGap(18, 18, 18)
                        .addComponent(crokeRB)
                        .addGap(18, 18, 18)
                        .addComponent(thomondRB)
                        .addGap(18, 18, 18)
                        .addComponent(kingspanRB))
                    .addGroup(addPLayout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPLayout.createSequentialGroup()
                        .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPLayout.createSequentialGroup()
                                .addComponent(typeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(concertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addPLayout.createSequentialGroup()
                                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(homeLabel)
                                    .addComponent(headlineLabel))
                                .addGap(18, 18, 18)
                                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(homeTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(headlineTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPLayout.createSequentialGroup()
                                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(awayLabel)
                                    .addComponent(supportLabel))
                                .addGap(18, 18, 18)
                                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(awayTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(supportTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                            .addComponent(matchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPLayout.createSequentialGroup()
                .addComponent(displayArray)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBtn))
        );
        addPLayout.setVerticalGroup(
            addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(concertBtn)
                    .addComponent(matchBtn))
                .addGap(18, 18, 18)
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(avivaRB)
                    .addComponent(crokeRB)
                    .addComponent(thomondRB)
                    .addComponent(kingspanRB))
                .addGap(18, 18, 18)
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLabel)
                    .addComponent(homeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(awayLabel)
                    .addComponent(awayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headlineLabel)
                    .addComponent(headlineTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supportLabel)
                    .addComponent(supportTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                .addGroup(addPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBtn)
                    .addComponent(submitBtn)
                    .addComponent(displayArray)
                    .addComponent(exportBtn)))
        );

        contentP.add(addP, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBActionPerformed
        contentP.setVisible(true);
        viewP.setVisible(true);
        addP.setVisible(false);
    }//GEN-LAST:event_viewBActionPerformed

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        contentP.setVisible(true);
        viewP.setVisible(false);
        addP.setVisible(true);
        headlineLabel.setVisible(false);
        headlineTF.setVisible(false);
        supportLabel.setVisible(false);
        supportTF.setVisible(false);
        homeLabel.setVisible(false);
        homeTF.setVisible(false);
        awayLabel.setVisible(false);
        awayTF.setVisible(false);
    }//GEN-LAST:event_addBActionPerformed

    private void concertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concertBtnActionPerformed
        state = true;
        
        headlineLabel.setVisible(true);
        headlineTF.setVisible(true);
        supportLabel.setVisible(true);
        supportTF.setVisible(true);
        homeLabel.setVisible(false);
        homeTF.setVisible(false);
        awayLabel.setVisible(false);
        awayTF.setVisible(false);
        
        
    }//GEN-LAST:event_concertBtnActionPerformed

    private void matchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchBtnActionPerformed
        state = false;
        
        headlineLabel.setVisible(false);
        headlineTF.setVisible(false);
        supportLabel.setVisible(false);
        supportTF.setVisible(false);
        homeLabel.setVisible(true);
        homeTF.setVisible(true);
        awayLabel.setVisible(true);
        awayTF.setVisible(true);
    }//GEN-LAST:event_matchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        
        headlineTF.setText("");
        supportTF.setText("");
        homeTF.setText("");
        awayTF.setText("");
        dateTF.setText("");
        headlineLabel.setVisible(false);
        headlineTF.setVisible(false);
        supportLabel.setVisible(false);
        supportTF.setVisible(false);
        homeLabel.setVisible(false);
        homeTF.setVisible(false);
        awayLabel.setVisible(false);
        awayTF.setVisible(false);
        
        JOptionPane.showMessageDialog(null, "The form has been cleared.");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        
        if(state == true){
            Event e = new Event();
            
            if(avivaRB.isSelected()){
                location = "Aviva Stadium";
            } else if(crokeRB.isSelected()){
                location = "Croke Park";
            } else if(thomondRB.isSelected()){
                location = "Thomond Park";
            } else if(kingspanRB.isSelected()){
                location = "Kingspan Stadium";
            }
            
            e.setLocation(location);
            
            e.setDate(dateTF.getText());
            
            name = headlineTF.getText()+" featuring: "+supportTF.getText();
            e.setName(name);
            
            type="Concert";
            e.setType(type);
            
            eList.add(e);
        }
        
        if(state == false){
            Event e = new Event();
            
            if(avivaRB.isSelected()){
                location = "Aviva Stadium";
            } else if(crokeRB.isSelected()){
                location = "Croke Park";
            } else if(thomondRB.isSelected()){
                location = "Thomond Park";
            } else if(kingspanRB.isSelected()){
                location = "Kingspan Stadium";
            }
            
            e.setLocation(location);
            
            e.setDate(dateTF.getText());
            
            name = homeTF.getText()+" Vs. "+awayTF.getText();
            e.setName(name);
            
            type="Match";
            e.setType(type);
            
            eList.add(e);
        }

        JOptionPane.showMessageDialog(null,"The event information has been saved!");
    }//GEN-LAST:event_submitBtnActionPerformed

    private void displayArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayArrayActionPerformed
        for (int i=0; i < eList.size(); i++){
            JOptionPane.showMessageDialog(null, "Name: "+eList.get(i).getName()+"\nType: "+eList.get(i).getType()+"\nAt "+eList.get(i).getLocation()+" on "+eList.get(i).getDate());
        }      
    }//GEN-LAST:event_displayArrayActionPerformed

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
//        File outFile;
//        FileOutputStream fStream;
//        ObjectOutputStream oStream;
//        
//        try{
//            outFile = new File("event.data");
//            fStream = new FileOutputStream(outFile);
//            oStream = new ObjectOutputStream(fStream);
//            
//            oStream.writeObject(eList);
//            
//            JOptionPane.showMessageDialog(null, "Event list exported successfully");
//            
//            oStream.close();
//        }
//        catch(IOException x){
//            System.out.println(eList);
//        }
//        }
    }//GEN-LAST:event_exportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JPanel addP;
    private javax.swing.JButton avivaBtn;
    private javax.swing.JLabel avivaLabel;
    private javax.swing.JRadioButton avivaRB;
    private javax.swing.JLabel awayLabel;
    private javax.swing.JTextField awayTF;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton concertBtn;
    private javax.swing.JPanel contentP;
    private javax.swing.JButton crokeBtn;
    private javax.swing.JLabel crokeLabel;
    private javax.swing.JRadioButton crokeRB;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTF;
    private javax.swing.JButton displayArray;
    private javax.swing.JButton exportBtn;
    private javax.swing.JLabel headlineLabel;
    private javax.swing.JTextField headlineTF;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JTextField homeTF;
    private javax.swing.JButton kingspanBtn;
    private javax.swing.JLabel kingspanLabel;
    private javax.swing.JRadioButton kingspanRB;
    private javax.swing.ButtonGroup locationBtnGroup;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JButton matchBtn;
    private javax.swing.JPanel navP;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel supportLabel;
    private javax.swing.JTextField supportTF;
    private javax.swing.JButton thomondBtn;
    private javax.swing.JLabel thomondLabel;
    private javax.swing.JRadioButton thomondRB;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JButton viewB;
    private javax.swing.JPanel viewP;
    // End of variables declaration//GEN-END:variables
}
